mplate_decoder/urls.py
from django.urls import path, re_path
from django.contrib import admin
from django.utils.translation import gettext as _
from . import views

app_name = 'mplate_decoder'
urlpatterns = [
     path('decode/', views.MplateCreate.as_view(),
          name='mplate_create'),
     re_path(r'^(?P<chassis_number_short>[0-9]{7,8})/$',
             views.MplateRetrieve.as_view(),
             name='mplate_retrieve'),
     re_path(r'^(?P<chassis_number_short>[0-9]{7,8})/update/$',
             views.MplateUpdate.as_view(),
             name='mplate_update'),
     re_path(r'^(?P<chassis_number_short>[0-9]{7,8})/delete/$',
             views.MplateDelete.as_view(),
             name='mplate_delete'),
     path('mine/', views.MplatesByUserListView.as_view(),
          name='mplate_mine'),
     path('', views.MplateIndex.as_view(),
          name='mplate_index'),
     path('about/', views.MplateAbout.as_view(),
          name='mplate_about'),
     path('search/', views.SearchResultsView.as_view(),
          name='search_results'),
     path('metrics/', views.MetricsView.as_view(),
          name='mplate_metrics'),
]

SITE_NAME = _("VW Type 2 ID")
admin.site.site_header = _(f"{SITE_NAME} Admin")
admin.site.site_title = _(f"{SITE_NAME} Admin Portal")
admin.site.index_title = _(f"Welcome to {SITE_NAME} Admin Portal")

users/urls.py
from django.urls import path
from .views import SignUp

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
]

vw_type2_id/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from . import settings
from django.contrib.staticfiles.urls import static


def trigger_error(request):
    division_by_zero = 1 / 0  # noqa: F841


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('mplate/', include('mplate_decoder.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('contact.urls')),
    path('sentry-debug/', trigger_error),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vw_type2_id/templates/base_bootstrap.html
{% load navactive %}
{% load static %}
{% load i18n %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-5WDHVS2QKP"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-5WDHVS2QKP');
    </script>

    <!-- Local CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% block style %}<!-- Additional styles -->{%endblock%}

    {% block title %}<title>{% trans "VW M-plate decoder" %}</title>{% endblock %}

    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">

  </head>

  <body>

    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">
        <img src="{% static 'img/logo-32x32.png' %}" width="30" height="30" alt="{% trans 'Volkswagen Type 2 identification' %}">
        <!-- VW Type 2 id -->
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <!-- Breadcrumbs -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% navactive request 'home' %}">
            <a class="nav-link" href="/">{% filter upper %} {% trans 'Home' %} {% endfilter %}</a>
          </li>
            <li class="nav-item {% navactive request 'mplate_decoder:mplate_index' %}">
            <a class="nav-link" href="{% url 'mplate_decoder:mplate_index' %}">{% filter upper %} {% trans 'M-Plate info' %} {% endfilter %}</a>
          </li>
          <li class="nav-item {% navactive request 'mplate_decoder:mplate_create' %}">
            <a class="nav-link" href="{% url 'mplate_decoder:mplate_create' %}">{% filter upper %} {% trans "M-Plate decoder" context "navbar" %} {% endfilter %}</a>
          </li>
          <li class="nav-item {% navactive request 'mplate_decoder:mplate_metrics' %}">
            <a class="nav-link" href="{% url 'mplate_decoder:mplate_metrics' %}">{% filter upper %} {% trans 'Metrics' %} {% endfilter %}</a>
          </li>
          <li class="nav-item {% navactive request 'mplate_decoder:mplate_about' %}">
            <a class="nav-link" href="{% url 'mplate_decoder:mplate_about' %}">{% filter upper %} {% trans 'About' %} {% endfilter %}</a>
          </li>
        </ul>
        <!-- Search box -->
        <form class="form-inline my-2 my-lg-0" action="{% url 'mplate_decoder:search_results' %}" method="get">
          <div class="input-group mr-sm-2">
            <input class="form-control" name="q" type="text" aria-label="Search" placeholder="{% trans 'Search M-codes (e.g. 500)' %}">
              <div class="input-group-append">
                <span class="input-group-text"><ion-icon name="search-outline"></ion-icon></span>
              </div>
          </div>
        </form>
        <!-- Authentication menu -->
        {% if user.is_authenticated %}
        <div class="dropdown">
          <a class="btn btn-outline-success dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'mplate_decoder:mplate_mine' %}">{% trans "My M-plates" %}</a>
            {% if user.is_superuser %}
            <a class="dropdown-item" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
            {% endif %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">{% trans "Log out" %}</a>
          </div>
        </div>
        
        {% else %}
        <a class="btn btn-outline-success ml-sm-2" href="{% url 'login' %}?next={{request.path}}">{% trans "Sign up or login" %}</a>           
        {% endif %}
      </div>
    </nav>

    <!-- Content -->
    <div class="container">
      {% block content %}<!-- Content here -->{% endblock %}
    </div>
    {% block contentnocontainer %}<!-- Content that defines its own container here -->{% endblock %}

    <!-- JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
		  src="https://code.jquery.com/jquery-3.4.1.min.js"
			integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			crossorigin="anonymous"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"></script>
    <script
      src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"
      integrity="SUKVFL96/F3W7HeIynfEsxa4KzwJDaMoDmUg55kklFVgIfxhDIrvEkQIHfLfGV2J"
      crossorigin="anonymous" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.2.2/anchor.min.js"
      integrity="sha256-E4RlfxwyJVmkkk0szw7LYJxuPlp6evtPSBDlWHsYYL8="
      crossorigin="anonymous"></script>

    {% block javascript %}<!-- Additional JavaScript -->{% endblock %}

  </body>
</html>

vw_type2_id/templates/home.html
{% extends "base_bootstrap.html" %}
{% load i18n %}

{% block contentnocontainer %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">{% trans "Volkswagen Type 2 identification" %}</h1>
    <p class="lead">{% trans "A set of tools to identify VW Type 2 vehicles for model years 1968 to 1979." %}</p>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md">
      <h2>{% trans "M-plate decoder" %}</h2>
      <p>{% trans "Decode the M-plate and find information about your bus." %}</p>
      <p><a class="btn btn-secondary" href="{% url 'mplate_decoder:mplate_index'%}" role="button">{% trans "Learn more &raquo;" %}</a></p>
    </div>
    <div class="col-md">
      <h2>{% trans "Engine number decoder" %}</h2>
      <p>{% trans "Coming soon" %}</p>
    </div>
</div>

{% endblock %}

vw_type2_id/templates/signup.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}

<div class="row justify-content-center mt-4">
  <div class="col-4">
    <div class="card">
      <div class="card-body">
        <h2 class="card-title">{% trans "Sign up" %}</h2>
        <form method="post" id="{{ form_id }}" action="">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-primary btn-block btn-lg mt-4">{% trans "Sign me up!" %}</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}