mplate_decoder/urls.py
from django.urls import path, re_path
from django.contrib import admin
from django.utils.translation import gettext as _
from . import views

app_name = 'mplate_decoder'
urlpatterns = [
     path('decode/', views.MplateCreate.as_view(),
          name='mplate_create'),
     re_path(r'^(?P<chassis_number_short>[0-9]{7,8})/$',
             views.MplateRetrieve.as_view(),
             name='mplate_retrieve'),
     re_path(r'^(?P<chassis_number_short>[0-9]{7,8})/update/$',
             views.MplateUpdate.as_view(),
             name='mplate_update'),
     re_path(r'^(?P<chassis_number_short>[0-9]{7,8})/delete/$',
             views.MplateDelete.as_view(),
             name='mplate_delete'),
     path('mine/', views.MplatesByUserListView.as_view(),
          name='mplate_mine'),
     path('', views.MplateIndex.as_view(),
          name='mplate_index'),
     path('about/', views.MplateAbout.as_view(),
          name='mplate_about'),
     path('search/', views.SearchResultsView.as_view(),
          name='search_results'),
     path('metrics/', views.MetricsView.as_view(),
          name='mplate_metrics'),
]

SITE_NAME = _("VW Type 2 ID")
admin.site.site_header = _(f"{SITE_NAME} Admin")
admin.site.site_title = _(f"{SITE_NAME} Admin Portal")
admin.site.index_title = _(f"Welcome to {SITE_NAME} Admin Portal")

users/urls.py
from django.urls import path
from .views import SignUp

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
]

vw_type2_id/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from . import settings
from django.contrib.staticfiles.urls import static


def trigger_error(request):
    division_by_zero = 1 / 0  # noqa: F841


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('mplate/', include('mplate_decoder.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('contact.urls')),
    path('sentry-debug/', trigger_error),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mplate_decoder/models.py
import re
import logging
from datetime import date, datetime
from django.db.models import Model, Q
from django.db import models
from django.urls import reverse
from django.forms import ValidationError
from django.core.exceptions import (
    ObjectDoesNotExist,
    MultipleObjectsReturned,
)
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext
from isoweek import Week
from crum import get_current_user

logger = logging.getLogger(__name__)


class Mplate(Model):
    class Meta:
        ordering = ['-id']

    _decoder = None

    chassis_number_short = models.CharField(
        _("Shortened chassis number"),
        max_length=8, unique=True,
        help_text=_("Chassis number shortened, with the two leading digits "
                    "removed."))
    m_codes_1 = models.CharField(
        _("M-codes, row 1"),
        max_length=19, blank=True,
        help_text=_("Row 1 of M codes (max 5)"))
    m_codes_2 = models.CharField(
        _("M-codes, row 2"),
        max_length=19, blank=True,
        help_text=_("Row 2 of M codes (max 4 -mod. '70-'79 or "
                    "5 -mod. '68-'69-)"))
    paint_and_interior_code = models.CharField(
        _("Paint and interior"),
        max_length=6,
        help_text=_('Combined VW body/roof paint and interior codes'))
    production_date_code = models.CharField(
        _("Production date"),
        max_length=3,
        help_text=_('Production date code'))
    production_planned = models.CharField(
        _("Production planning"),
        max_length=4, blank=True,
        help_text=_('Production planning code'))
    export_destination_code = models.CharField(
        _("Export destination"),
        max_length=3, blank=True,
        help_text=_('Export destination code'))
    model_code = models.CharField(
        _("Vehicle model"),
        max_length=4,
        help_text=_('Vehicle model code'))
    aggregate_code = models.CharField(
        _("Aggregate"),
        max_length=2,
        help_text=_('Engine and gearbox aggregate code'))
    emden = models.CharField(
        _("Emden"),
        max_length=1, blank=True,
        help_text=_('Optional "E" for Emden'))
    created_at = models.DateTimeField(
        auto_now_add=True, blank=True,
        null=True)
    updated_at = models.DateTimeField(
        auto_now=True, blank=True,
        null=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        editable=False,
        blank=True, null=True, default=None)
    editor_remarks = models.TextField(
        blank=True)

    # Computed (decoded) fields
    m_codes = models.CharField(
        max_length=38, blank=True, editable=False,
        help_text=_("Full list of M codes for this M plate"))
    production_date_as_time = models.DateField(
        blank=True, editable=False,
        help_text=_("Planned production date, in time format"))
    model_year = models.CharField(
        max_length=4, blank=True, editable=False,
        help_text=_('Model year'))
    destination_country = models.CharField(
        max_length=70, blank=True,
        help_text=_("Country of destination"))

    def __unicode__(self):
        return self.chassis_number_short

    def get_absolute_url(self):
        '''
        Return the Mplate objects canonical URL. Required for the admin's
        "View on site" feature to work:
        https://docs.djangoproject.com/en/2.2/ref/models/instances/#get-absolute-url
        '''
        return reverse(
            'mplate_decoder:mplate_retrieve',
            kwargs={'chassis_number_short': self.chassis_number_short})

    @property
    def decoder(self):
        '''
        Return the object used to decode all the various M-plate codes
        '''
        if not self._decoder:
            decoder = MplateDecoder(self)
        else:
            decoder = self._decoder

        return decoder

    @property
    def serial_production_number(self):
        '''
        Return the bus' 6-digit serial production number
        '''
        _MODEL_YEAR_SERIAL_NR_SPLIT_AT = -6
        splitat = _MODEL_YEAR_SERIAL_NR_SPLIT_AT
        serial_number = int(self.chassis_number[splitat:])

        return serial_number

    @property
    def chassis_number(self):
        '''
        Return the bus' full chassis (VIN) number
        '''
        type_body = self.model_code[:2]

        return type_body + self.chassis_number_short

    @property
    def model(self):
        '''
        Decoded vehicle model object
        '''
        return self.decoder.decode_model()

    @property
    def exteriorcolor_code(self):
        return self.decoder.get_exteriorcolor_code()

    @property
    def export_destination(self):
        return self.decoder.decode_export_destination()

    @property
    def exteriorcolor(self):
        return self.decoder.decode_exteriorcolor()

    def describe_model(self):
        return self.decoder.describe_model()

    def describe_export_destination(self):
        return self.decoder.describe_export_destination()

    def describe_export_destination_country(self, with_port=True):
        return self.decoder.describe_export_destination_country(with_port)

    def describe_exteriorcolor(self):
        return self.decoder.describe_exteriorcolor()

    def _decode_model_year(self):
        '''Used to compute property before saving'''
        return self.decoder.decode_model_year()

    def _decode_production_date(self):
        '''Used to compute property before saving'''
        return self.decoder.decode_production_date()

    def _get_exteriorcolorchip(self):

        color_chip_body = ""
        color_chip_roof = ""

        # Get the exterior color object from the M-plate
        # code
        exteriorcolor = self.exteriorcolor

        if exteriorcolor:
            try:
                # Get the color attributes from the lacquer code
                color_body = Color.objects.get(
                    lacquer_code=exteriorcolor.lacquer_code_body
                )
                # Get the color chip
                color_chip_body = color_body.chip
            except ObjectDoesNotExist:
                logger.warning('Body color chip does not exist')
                color_chip_body = ""

            try:
                # Get the color attributes from the lacquer code
                color_roof = Color.objects.get(
                    lacquer_code=exteriorcolor.lacquer_code_roof
                )
                # Get the color chip
                color_chip_roof = color_roof.chip
            except ObjectDoesNotExist:
                logger.warning('Body color chip does not exist')
                color_chip_roof = ""

        return (color_chip_body, color_chip_roof)

    def describe_interiorcolor(self):
        SPECIAL_PAINTJOB_ID = '5'
        model_year = 0

        if not self.paint_and_interior_code.startswith(SPECIAL_PAINTJOB_ID):
            interiorcolor_code = self.paint_and_interior_code[-2:]

            try:
                interiorcolor = InteriorColor.objects.get(
                    plate_code=interiorcolor_code
                )
                color_name = interiorcolor.color_name
                material = interiorcolor.material
            except ObjectDoesNotExist:
                color_name = _(f"({interiorcolor_code}) Unknown color")
                material = _("Unknown material")
            except MultipleObjectsReturned:
                model_year = self.model_year
                interiorcolor = InteriorColor.objects.filter(
                    plate_code=interiorcolor_code,
                    years__contains=model_year,
                )
                if interiorcolor:
                    color_name = interiorcolor.first().color_name
                    material = interiorcolor.first().material
                else:
                    color_name = (
                        _("Error while fetching interior color code:") +
                        gettext(f" {interiorcolor_code}, year {model_year}"))
                    material = _("Unknown material")
                    logger.error(color_name)

            interiorcolor_description = '{}, {}'.format(color_name, material)
        else:
            interiorcolor_description = (
                _('No description available for special paint jobs'))

        return interiorcolor_description

    def get_engine(self):
        engine_code = self.aggregate_code[0]

        try:
            engine = Engine.objects.get(
                engine_code=engine_code
            )
            engine_description = '{}, {}'.format(
                engine.engine_type,
                engine.fuel_induction,
            )
            if engine.extra_specs:
                engine_description += ", " + engine.extra_specs

        except ObjectDoesNotExist:
            engine_description = _("Unavailable engine description")
            logger.error(engine_description)

        return engine_description

    def get_gearbox(self):
        gearbox_code = self.aggregate_code[1]

        try:
            gearbox = Gearbox.objects.get(
                gearbox_code=gearbox_code
            )
            gearbox_description = '{}'.format(
                gearbox.gearbox_description,
            )
        except ObjectDoesNotExist:
            gearbox_description = _("Unavailable transmission description")

        return gearbox_description

    def save(self, *args, **kwargs):

        # Calculate the full m_codes field
        self.m_codes = f"{self.m_codes_1} {self.m_codes_2}"

        # Calculate model year
        self.model_year = self._decode_model_year()

        # Calculate production date
        self.production_date_as_time = self._decode_production_date()

        # Calculate destination country
        self.destination_country = \
            self.describe_export_destination_country(with_port=False)

        # Calculate owner

mplate_decoder/templates/mplate_decoder/detail.html
{% extends "mplate_base_bootstrap.html" %}

{% load static %}
{% load svg %}
{% load i18n %}

{% block content %}

<div class="row">
<div class="col-sm-6 mt-4">
{{ plate|safe }}
</div>
<div class="col-sm-6 mt-4">
{% if schematic %}
{{ schematic|safe }}
{% endif %}
</div>
</div>

<div class="row mt-4">
<div class="col">
<h2>{% trans "Specifications" %}</h2>
<div class="table-responsive">
<table class="table table-hover">
  <tr>
    <td><strong>{% filter upper %} {% trans 'Model' %} {% endfilter %}</strong></td> 
    <td>{% trans "Volkswagen Type 2" %}<br>
    {% blocktrans with model_description=model_description.model_description model_code_catalog=model_description.model_code_catalog configuration_description=model_description.configuration_description extras_description=model_description.extras_description %}
        ➡ {{ model_description }} (model {{ model_code_catalog }})<br>
        ➡ {{ configuration_description }}<br>
        ➡ {{ extras_description }}<br>
    {% endblocktrans %}
    </td>
  </tr>
  <tr>
    <td><strong>{% filter upper %} {% trans 'Model year' %} {% endfilter %}</strong></td> 
    <td>{{ model_year }}</td>
  </tr>
  <tr>
    <td><strong>{% filter upper %} {% trans 'Engine' %} {% endfilter %}</strong></td> 
    <td>{{ engine_description }} </td>
  </tr>
  <tr>
    <td><strong>{% filter upper %} {% trans 'Transmission' %} {% endfilter %}</strong></td> 
    <td>{{ gearbox_description }} </td>
  </tr>
  <tr>
    <td><strong>{% filter upper %} {% trans 'Vehicle Ident. Nr.' %} {% endfilter %}</strong></td> 
    <td>{{ chassis_number }}</td>
  </tr>
  <tr>
    <td><strong>{% filter upper %} {% trans 'Production date' %} {% endfilter %}</strong></td> 
    <td id="production-date">
        {{ production_date }}{% if emden %}. Manufactured at the Emden plant
            <ion-icon
              class="icon"
              data-toggle="tooltip"
              title="From December 1967 to April 1973, as the Hannover plant was over capacity"
              name="information-circle-outline">
            </ion-icon>
        {% endif %}
    </td>
  </tr>
  <tr>
    <td><strong>{% filter upper %} {% trans 'Optional extras' %} {% endfilter %}</strong></td> 
    <!-- <td>{{ mplate.m_codes_1 }} {{ mplate.m_codes_2 }}</td> -->
    <td>
    {% for key, value in m_codes.items %}
        {{ key }}: {{ value }} <br>
    {% endfor %}
    </td>
  <tr>
    <td><strong>{% filter upper %} {% trans 'Exterior' %} {% endfilter %}</strong></td> 
    <td>{{ exteriorcolor_description|linebreaksbr }} </td>
  </tr>  
  <tr>
    <td><strong>{% filter upper %} {% trans 'Interior' %} {% endfilter %}</strong></td> 
    <td>{{ interiorcolor_description }} </td>
  </tr>
  {% if export_destination and 'Unknown' not in export_destination and 'Not specified' not in export_destination %}
  <tr>
    <td><strong>{% filter upper %} {% trans 'Destination' %} {% endfilter %}</strong></td>
    <td>{{ export_destination }} </td>
  </tr>
  {% endif %}
  {% if export_destination_country %}
  <tr>
    <td><strong>{% filter upper %} {% trans 'Destination country' %} {% endfilter %}</strong></td>
    <td>{{ export_destination_country }} </td>
  </tr>
  {% endif %}
</table>
</div>
</div>
</div>

{% endblock %}

{% block javascript %}
<script type="text/javascript">
  $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
</script>
{% endblock %}

mplate_decoder/templates/mplate_decoder/index.html
{% extends "mplate_base_bootstrap.html" %}
{% load svg %}
{% load humanize %}
{% load i18n %}

{% block content %}

<!-- Intro row -->
<div class="row mt-4">
  <div class="col">
    <p class="lead">
    {% blocktrans %}
      The M-plate is one of the identification plates found on VW busses. 
      Short for <em>Mehraustattung</em> (optional extras in German), it contains
      production codes with information about equipment, manufacturing date, destination, specs and more.
    {% endblocktrans %}
    </p>
  </div>
</div>

<!-- Location rows -->
<div class="row mt-4">
  <div class="col-sm">
    <h2>{% trans "Find it" %}</h2>
  </div>
</div>

<div class="row mt-4">
  <div class="col-sm">
    <h4>
      <span class="text-muted">{% trans "Model years 68-76" %}</span>
    </h4>
    <img class="img-fluid img-thumbnail" src="https://www.thesamba.com/vw/gallery/pix/2000905.jpg">
    <p><small class="text-muted">
    {% blocktrans with url_forum='https://www.thesamba.com/vw/forum/viewtopic.php?p=7551789' url_img='https://www.thesamba.com/vw/forum/album_page.php?pic_id=1901273' %}
    Image modified from <a href="{{ url_img }}">The Samba forum</a> and <a href="{{ url_img }}">album</a>
    {% endblocktrans %}
    </small></p>
    <p class="mt-1">
      {% trans "<strong>Before model year 1977</strong>: the M-plate is located on the metal partition behind the driver's seat (passenger's seat for RHD vehicles)." %}
    </p>
  </div>

  <div class="col-sm">
    <h4>
      <span class="text-muted">{% trans "Model years 77-79" %}</span>
    </h4>
    <img class="img-fluid img-thumbnail" src="https://www.thesamba.com/vw/gallery/pix/2000904.jpg">
      <p><small class="text-muted">
      {% blocktrans with url='https://www.thesamba.com/vw/forum/viewtopic.php?p=7551789' %}
      Image modified from <a href="{{ url }}">The Samba forum</a>
      {% endblocktrans %}
      </small></p>
      <p class="mt-1">
        {% trans "<strong>Model year 1977 and after</strong>: the M-plate is located under the dashboard, on top of the metal fresh air pipe." %} 
      </p>
  </div>
</div>

<!-- Decoder rows -->
<div class="row mt-4">
  <div class="col-sm">
    <h2>{% trans "Decode it" %}</h2>
  </div>
</div>

<div class="row mt-4">
  <div class="col-sm">
  <h4 class="mb-3">{% trans "M-plate decoder" %}</h4>
  <div>
    {% svg 'mplate-7079-form' %}
  </div>
  <p class="mt-3">
    {% trans "Use the automatic decoder to find out more about the original configuration, equipment and extras for a Type 2 bus. Simply choose the model year and fill in the M-plate fields." %}  </p>
  
  <div>
    <a class="btn btn-primary btn-lg btn-block mt-3 mb-4" href="{% url 'mplate_decoder:mplate_create' %}" role="button">{% trans "Decode an M-plate&raquo;" %}</a>
  </div>
</div>

<div class="col-sm">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-muted">{% trans "M-plate submissions" %}</span>
      <span class="badge badge-secondary badge-pill">{{ object_list.count }}</span>
    </h4>
    <ul class="list-group">
        {% for mplate in object_list|dictsortreversed:"id"|slice:":7" %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <h6 class="my-1 text-info no-anchor">
                <a href="{% url 'mplate_decoder:mplate_retrieve' mplate.chassis_number_short %}">{{ mplate.chassis_number_short }}</a>
                <span class="badge badge-secondary badge-pill">{{ mplate.model_year }}</span>
                {% if mplate.destination_country %}
                <span class="badge badge-secondary badge-pill">{{ mplate.destination_country }}</span>
                {% endif %}
              </h6>
              <span class="badge badge-info badge-pill">{{ mplate.created_at|naturalday }}</span>
            </li>
        {% endfor %}
    </ul>
</div>

</div>

<div class="row mt-4">

</div>

{% endblock %}

mplate_decoder/templates/mplate_decoder/metrics.html
{% extends "mplate_base_bootstrap.html" %}
{% load i18n %}

{% block content %}

<div class="row">
  <div class="col">
    <p class="lead mt-4">
      {% trans "Vehicle production data extracted from the M-plate decoder submissions" %}
    </p>
  </div>
</div>

<div class="row my-4">
  <div class="col">
    <h2 class='mt-4'>{% trans "Top 10 models" %}</h2>
    <canvas id="models-chart"></canvas> 
  </div>
  <div class="col">
    <h2 class='mt-4'>{% trans "Model years" %}</h2>
    <canvas id="years-chart"></canvas>
  </div>
</div>

<div class="row my-4">
  <div class="col">
    <h2 class='mt-4'>{% trans "Top 15 colors" %}</h2>
    <canvas id="colors-chart"></canvas> 
  </div>
  <div class="col">
    <h2 class='mt-4'>{% trans "Top 10 destination countries" %}</h2>
    <canvas id="countries-chart"></canvas>
  </div>
</div>

<div class="row my-4">
  <div class="col">
    <h2 class='my-4'>{% trans "Daily M-plate submissions" %}</h2>
    <canvas id="submissions-chart"></canvas> 
  </div>
</div>

{% endblock %}

{% block javascript %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js"
        integrity="sha256-TQq84xX6vkwR0Qs1qH5ADkP+MvH0W+9E7TdHJsoIQiM="
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-colorschemes"></script>

<script>
  var timeFormat = 'YYYY-MM-DD';

  var configSubmissions = {
    type: 'line',
    data: {
      datasets: [{
        data: {{ submissionsData|safe }},
        label: "{% trans 'M-plate submissions' %}"
      }],
      labels: {{ submissionsLabels|safe }},
    },
    options: {
      responsive: true,
      legend: {
        display: false,
      },
      scales: {
        xAxes: [{
          type: "time",
          time: {
            parser: timeFormat,
            tooltipFormat: 'll'
          },
          scaleLabel: {
            display: true,
            labelString: "{% trans 'Date' %}"
          }
        }],
        yAxes: [{
          scaleLabel: {
            display: true,
            labelString: "{% trans 'M-plate submissions' %}"
          }
        }]
      }
    }
  };
  
  var configModels = {
    type: 'doughnut',
    data: {
      datasets: [{
        data: {{ modelsData|safe }},
        label: "{% trans 'VW Type 2 models' %}"
      }],
      labels: {{ modelsLabels|safe }}
    },
    options: {
      responsive: true,
      circumference: Math.PI,
      rotation: -Math.PI,
      plugins: {
          colorschemes: {
              scheme: 'tableau.Tableau10'
          }
      }
    }
  };
  var configYears = {
    type: 'doughnut',
    data: {
      datasets: [{
        data: {{ yearsData|safe }},
        label: "{% trans 'Model year' %}"
      }],
      labels: {{ yearsLabels|safe }}
    },
    options: {
      responsive: true,
      plugins: {
          colorschemes: {
              scheme: 'brewer.Paired12'
          }
      }
    }
  };
  var configColors = {
    type: 'doughnut',
    data: {
      datasets: [{
        data: {{ colorsData|safe }},
        label: "{% trans 'Color' %}",
        backgroundColor: {{ colorsBackgroundColor|safe }},
      }],
      labels: {{ colorsLabels|safe }}
    },
    options: {
      responsive: true,
      circumference: Math.PI,
      rotation: -Math.PI,
      plugins: {
          colorschemes: {
              scheme: 'brewer.Paired12'
          }
      }
    }
  };
  var configCountries = {
    type: 'doughnut',
    data: {
      datasets: [{
        data: {{ countriesData|safe }},
        label: "{% trans 'Countries' %}"
      }],
      labels: {{ countriesLabels|safe }}
    },
    options: {
      responsive: true,
      circumference: Math.PI,
      rotation: -Math.PI,
      plugins: {
          colorschemes: {
              scheme: 'tableau.Winter10'
          }
      }
    }
  };
  window.onload = function() {
    var ctxSubmissions = document.getElementById('submissions-chart').getContext('2d');
    window.submissionsTimeseries = new Chart(ctxSubmissions, configSubmissions);
    var ctxModels = document.getElementById('models-chart').getContext('2d');
    window.modelsPie = new Chart(ctxModels, configModels);
    var ctxYears = document.getElementById('years-chart').getContext('2d');
    window.yearsPie = new Chart(ctxYears, configYears);
    var ctxColors = document.getElementById('colors-chart').getContext('2d');
    window.colorsPie = new Chart(ctxColors, configColors);
    var ctxCountries = document.getElementById('countries-chart').getContext('2d');
    window.countriesPie = new Chart(ctxCountries, configCountries);
  };
</script>
{% endblock %}

mplate_decoder/templates/mplate_decoder/mplate_confirm_delete.html
{% extends "mplate_base_bootstrap.html" %}
{% load i18n %}

{% block content %}

<div class="row mt-4">
<div class="col">
<h1>{% trans "Delete M-plate" %}</h1>

<p>{% blocktrans %}Are you sure you want to delete M-plate {{ mplate.chassis_number_short }}?{% endblocktrans %}</p>

<form action="" method="POST">
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">{% trans "Yes, delete it" %}</button>
</form>
</div>
</div>

{% endblock %}

mplate_decoder/templates/mplate_decoder/mplate_created_by_user.html
{% extends "mplate_base_bootstrap.html" %}
{% load i18n %}

{% block content %}

<div class="row">
  <div class="col my-5">

    <h2 class="mb-4">{% trans "My M-plates" %}</h2>
      <div class="table-responsive">
        <table class="table table-hover">
          <tr>
            <th><strong>{% filter upper %} {% trans 'M-plate ID' %} {% endfilter %}</strong></th> 
            <th><strong>{% filter upper %} {% trans 'Model year' %} {% endfilter %}</strong></th>
            <th><strong>{% filter upper %} {% trans 'Actions' %} {% endfilter %}</strong></th>            
          </tr>
    {% if mplate_list %}
      {% for mplate in mplate_list %}
          <tr>
            <td><a href="{% url 'mplate_decoder:mplate_retrieve' mplate.chassis_number_short %}">{{ mplate.chassis_number_short }}</a></td>
            <td>{{ mplate.model_year }}</td>
            <td>
              <a class="btn btn-primary btn-sm" role="button" href="{% url 'mplate_decoder:mplate_update' mplate.chassis_number_short %}">{% trans "Edit" %}</a>
              <a class="btn btn-outline-danger btn-sm" role="button" href="{% url 'mplate_decoder:mplate_delete' mplate.chassis_number_short %}">{% trans "Delete" %}</a>
             </td>
          </tr>
      {% endfor %}
    {% else %}
          <tr>
            <td>{% trans "N/A" %}</td>
            <td>{% trans "N/A" %}</td>
            <td>{% trans "N/A" %}</td>
          </tr>
    {% endif %}
        </table>
      </div>
  </div>
</div>

{% endblock %}

mplate_decoder/templates/mplate_decoder/mplate_form.html
{% extends "mplate_base_bootstrap.html" %}

{% load static %}
{% load i18n %}

{% block content %}
{% with mplate_form_7079_id="mplate_form_7079" mplate_form_6869_id="mplate_form_6869" %}

  <div class="row mt-5">
  <div class="col">

  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="mod6869-tab" data-toggle="tab" href="#mod6869" role="tab" aria-controls="mod6869" aria-selected="true">{% trans "Model 68-69" %}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="mod7079-tab" data-toggle="tab" href="#mod7079" role="tab" aria-controls="mod7079" aria-selected="false">{% trans "Model 70-79" %}</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="mod6869" role="tabpanel" aria-labelledby="mod6869-tab">
      {% include "mplate_decoder/partials/mplate_form_6869.html" with form_id=mplate_form_6869_id %}
    </div>
    <div class="tab-pane fade" id="mod7079" role="tabpanel" aria-labelledby="mod7079-tab">
      {% include "mplate_decoder/partials/mplate_form_7079.html" with form_id=mplate_form_7079_id %}
    </div>
  </div>

  </div>
  </div>
{% endwith %}
{% endblock %}

{% block javascript %}

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script type="text/javascript" src="{% static 'js/ajaxformsubmit.js' %}"></script>
<script>
  $( document ).ready(function() {
      $(".chassis_number_short-6869 #id_chassis_number_short").attr('maxlength','7');
  });

  anchors.options.placement = 'left';
  document.addEventListener('DOMContentLoaded', function(event) {
    anchors.add();
  });
</script>

{% endblock %}